### ISSUE TITLE
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by fyyyyy** [sidebase/nuxt-auth#311]
### Environment

sidebase.io all options checked

### Reproduction

setup an oauth provider in [...].ts but it also seems to happen when using CredentialsProvider

The error happens on redirect to the /api/auth/signin page, as well as clicking signout

### Describe the bug

[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at setResponseHeader (file:///node_modules/h3/dist/index.mjs:670:18)
    at Object.errorhandler [as onError] (file:///.nuxt/dev/index.mjs:644:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.toNodeHandle (file:///node_modules/h3/dist/index.mjs:1329:9) {
  code: 'ERR_HTTP_HEADERS_SENT'

### Additional context
In production (i.e. vercel) this will sometimes even render the error page

**Comment by fyyyyy** [comment]
I noticed, that the first error for Signin does not happen if you replace the <a href="/protected"> with a button @click=navigateTo("/protected") in the sidebase project.

**Comment by fyyyyy** [comment]
The signout error is also avoidable by supplying a callbackUrl to the signout
```
<n-button
        type="error"
        @click="signOut({
          callbackUrl: '/'
        })"
      >
        sign out
      </n-button>
```

**Comment by BracketJohn** [comment]
Hey @fyyyyy 👋 

I think this was resolved via https://github.com/nuxt/nuxt/issues/20038 in nuxt 3.4.1? Please try it out again and let us know if the problem persists.

If the problem persists: Please provide a reproduction repository, that show-cases this concrete error (: See https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction for more

**Comment by fyyyyy** [comment]
unfortunately this fix in 3.4.1 did not resolve the issue https://github.com/nuxt/nuxt/issues/20038
![image](https://user-images.githubusercontent.com/3744048/232880070-eeb0f8cb-5bc8-485d-bfb7-2ca7433bdc2f.png)
Module.sendRedirect /node_modules/h3/dist/index.mjs:652:18
node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:23:82
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Object.callAsync node_modules/unctx/dist/index.mjs:72:16)
code: 'ERR_HTTP_HEADERS_SENT'

**Comment by joneath** [comment]
I'm still seeing it in my basic logout page. In dev it's a silent error but on Vercel it throws a 500.
```
<template>
  <div>LOGGING OUT</div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'auth' })

const { signOut } = useAuth()

signOut()
</script>
```

**Comment by BracketJohn** [comment]
>  It happens with you access an unauthorized route, i.e. the /protected route, in the sidebase default project.

thanks! just a quick q: which project do you mean by defualt project - this one or the example repo?

**Comment by BracketJohn** [comment]
Quick note: This may very well be a Nixt 3 upstream problem https://github.com/nuxt/nuxt/issues/20432

**Comment by fyyyyy** [comment]
> > It happens with you access an unauthorized route, i.e. the /protected route, in the sidebase default project.
> 
> thanks! just a quick q: which project do you mean by defualt project - this one or the example repo?

When creating a new repo 
npm create sidebase@latest
with nuxt-auth, prisma, tailwind, trpc, naive

**Comment by BracketJohn** [comment]
So this should be resolved in newest nuxt versions, let me know if it persists for you + posta reproduction for it, thanks!

**Comment by kecoliva** [comment]
I'm getting this error too.

**Comment by warflash** [comment]
@oau-dev @kecoliva Did you guys by chance manage to find a solution for this?

**Comment by hunter-isaiah96** [comment]
Yea still getting this error when I use the signout function.

**Comment by Smart-Ace-Designs** [comment]
For signout I was able to resolve this problem by adding a callbackUri:
```
const handleSignOut = () => {
  signOut({ callbackUrl: "/login" });
};
```

But I too am still having the problem when using a custom login page.  It hits the root (index.vue) and redirects to the login page (login.vue) and generates the error in the server console.  Everything appears to work and also has no problem when published to Netlify or on the DEV server.  But seeing errors makes me nervous :smile:

I am just wondering if there is any update to this?
Thank you for your time and for providing the Nuxt Auth module for us to use.
